#!/bin/bash

function check_root() {
  if [[ "$EUID" -ne "0" ]];then
    echo "Scripts must be run as root."
    exit 1
  fi
}

function update() {
  apt update && apt upgrade -y && apt autoremove -y
}

function install_desktop() {
  apt install tasksel -y
  tasksel install ubuntu-desktop ubuntu-desktop-default-languages
}

function install_genie() {
  wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
  dpkg -i packages-microsoft-prod.deb
  apt install dotnet-runtime-3.1 -y

  echo "deb [trusted=yes] https://wsl-translinux.arkane-systems.net/apt/ /" > /etc/apt/sources.list.d/wsl-translinux.list
  apt update
  apt install systemd-genie -y
}

function copy_file() {
  current_user=$(bash -c 'echo $SUDO_USER')
  cp ./.start_genie /home/${current_user}/.start_genie
  chmod +x /home/${current_user}/.start_genie
}

function setup_xdmcp() {
  apt install lightdm -y
  echo "[LightDM]" > /etc/lightdm/lightdm.conf
  echo "start-default-seat=false" >> /etc/lightdm/lightdm.conf
  echo "" >> /etc/lightdm/lightdm.conf
  echo "[XDMCPServer]" >> /etc/lightdm/lightdm.conf
  echo "enabled=true" >> /etc/lightdm/lightdm.conf
  echo "port=177" >> /etc/lightdm/lightdm.conf
  genie -c "sudo service lightdm restart"
}

function main() {
  check_root
  update
  install_desktop
  install_genie
  copy_file
  setup_xdmcp
}

main
